### ISSUE TITLE
not poggers

### ISSUE THREAD

**Issue by James-Li-t** [vcarnovale/survey-prog_chatgpt#1]
please make it poggers

**Comment by vcarnovale** [comment]
Its been poggified

**Comment by James-Li-t** [comment]
> Its been poggified

![Photo on 2023-04-15 at 1 47 PM](https://github.com/vcarnovale/survey-prog_chatgpt/assets/41440719/bd4ff87b-88f4-4904-994c-c5ed98e86261)
